# Generated by Django 2.2.2 on 2019-07-13 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_list', models.CharField(max_length=200)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cost', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
