# Generated by Django 2.2.2 on 2019-07-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_list',
            new_name='order_item',
        ),
    ]
